### ISSUE TITLE
Unfinished sentence in index.md

### ISSUE THREAD

**Issue by kieranjol** [UAlbanyArchives/mailbag#1]
Super exited for this project btw, especially curious if your tool allows for the creation of WARCs. Anyhow, to the issue!
In index.md, there's a sentence that is not complete 'Mailbags will also contain specific'.

Best,

Kieran O'Leary
Digital Preservation Manager
National Library of Ireland

**Comment by gwiedeman** [comment]
Thanks for catching this bad c+p @kieranjol !

We do plan on including an option to create and package WARCs for email using existing tools. Potentially using [warcio](https://github.com/webrecorder/warcio) or [wget](https://wiki.archiveteam.org/index.php/Wget_with_WARC_output). Would be great to have any feedback you might have on the [design docs](https://archives.albany.edu/mailbag/design_docs/)!

**Comment by kieranjol** [comment]
I will definitely read and provide feedback!
