### ISSUE TITLE
MBOX parser

### ISSUE THREAD

**Issue by gwiedeman** [UAlbanyArchives/mailbag#20]
## The problem the component solves

Mailbag needs to be able to read data from MBOX files to create mailbags. This parser needs to be interchangeable with other format parsers, so it should output data into an abstracted Input class

## Relevant part of mailbag spec?

...

## Type of component

- [ ] Core
- [X] Input
- [ ] Attachments
- [ ] Derivatives conversion
- [ ] Reporting/Exporting
- [ ] GUI
- [ ] Distribution

## Expected contribution

- [X] Pull Request
- [ ] Comment with proposed solution

## Major challenges or things to keep in mind

Email exports can be messy. We'll need a good amout of sample data and to document edge cases.

**Comment by baibhavr** [comment]
A new branch for this issue has been pushed. [mbox_parser branch](https://github.com/UAlbanyArchives/mailbag/tree/mbox_parser)

For now, in the parser.py, the _allMails_ list stores all the parsed emails where each mail is in key-value pair format.
