### ISSUE TITLE
PST parser

### ISSUE THREAD

**Issue by gwiedeman** [UAlbanyArchives/mailbag#23]
## The problem the component solves

Mailbag needs to be able to read data from PST files to create mailbags. This parser needs to be interchangeable with other format parsers, so it should output data into an abstracted Input class.

## Relevant part of mailbag spec?

...

## Type of component

- [ ] Core
- [X] Input
- [ ] Attachments
- [ ] Derivatives conversion
- [ ] Reporting/Exporting
- [ ] GUI
- [ ] Distribution

## Expected contribution

- [X] Pull Request
- [X] Comment with proposed solution

## Major challenges or things to keep in mind

Email exports can be messy. We'll need a good about of sample data and to document edge cases.

There doesn't seem to be a great tool for parsing PSTs, particularly on Windows.
* [libpff](https://github.com/libyal/libpff)
* [libpst](https://www.five-ten-sg.com/libpst/)

**Comment by haritgarg** [comment]
@gwiedeman I dont know why but I am not able to push my local branch into the github.

I have begin with parsing pst data and for able to get individual mails and associated content like subject and sender information but I am not able to push it to github.

also for my code to work we need to install libpff on our systems and import pypff.

I have not formed this into the required parse pst code yet but it is good to understand what we can extract from a pst file.
I will try to resolve the push issue as soon as possible.


# This is a sample Python script.

# Press Shift+F10 to execute it or replace it with your code.
# Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

import sys
import io

import pypff
import pandas as pd

pst = pypff.file()
pst.open("test.pst")

root = pst.get_root_folder()

def parse_folder(base):
    messages = []
    count = 0
    for folder in base.sub_folders:
        if folder.number_of_sub_folders:
            messages += parse_folder(folder)
            #print(messages)
        print(folder.name)
        for message in folder.sub_messages:
            count = count + 1
            messages.append({
                "subject": message.subject,
                "sender": message.sender_name,
                "attachment_count": message.number_of_attachments,
                #"submit_time": message.client_submit_time
                #"total_attachment_size": total_attachment_size_bytes,
                #"attachments": attachments
                #"creation_time": message.creation_time,
                #"submit_time": message.client_submit_time
            })
        print(count)
    return messages

messages = parse_folder(root)


df = pd.DataFrame(messages)
print(df)

**Comment by gwiedeman** [comment]
Just at-ing @baibhavr to test libpff on Linix when he gets a chance.

**Comment by gwiedeman** [comment]
Addressed with #47
