### ISSUE TITLE
Apply exclusions to original files

### ISSUE THREAD

**Issue by gwiedeman** [UAlbanyArchives/mailbag#25]
## The problem the component solves

Users may way to exclude lists of messages or folders that they want to exclude from a mailbag. Thus, we'll have to remove these from the original input files, such as MBOX and PST when including them the mailbag.

## Type of component

- [ ] Core
- [x] Input
- [ ] Attachments
- [ ] Derivatives conversion
- [ ] Reporting/Exporting
- [ ] GUI
- [ ] Distribution

## Expected contribution

- [x] Pull Request
- [ ] Comment with proposed solution

**Comment by gwiedeman** [comment]
This is on hold because excluding messages from PSTs in particular isn't feasible. We have to reexamine what the purpose and priority of this is.

**Comment by pobocks** [comment]
IMHO It might make more sense to implement this as a separate tool/tools or
even defer to a guide to existing tools?  Like, bagging is a metadata +
fixity step at core, and it's a little weird maybe to have this kind of
alteration as a part of a tool aimed at fixity operations?

I guess the counter argument is that doing it in-tool would allow for
recording metadata about the exclusions in the mailbag, I'm I think outside
my expertise re: archival process here tbh.

**Comment by gwiedeman** [comment]
@pobocks 's comment is reasonable. The issue is that there isn't great upstream tooling for, say, PSTs, and the filtering described by #28 would be useful if we ever implement IMAP or API sources. As described with [#28](https://github.com/UAlbanyArchives/mailbag/issues/28#issuecomment-1100121070), we would have to not package the source files which has limitations. Thus I'm closing this and leaving #28 open as the single issue for this. This feature is de-prioritized unless we get community feedback valuing it, or whenever IMAP or API parsers are implemented.
