### ISSUE TITLE
Mailbag should be able to load user-provided formats so as to be extensible.

### ISSUE THREAD

**Issue by pobocks** [UAlbanyArchives/mailbag#56]
**Is your feature request related to a problem? Please describe.**
As a consumer of mailbag, I'd like to be able to handle email formats that the software doesn't, or customize the handling of existing email formats.

**Describe the solution you'd like**
Mailbag should load formats provided by users from known or specified directories.

**Comment by gwiedeman** [comment]
For this do you mean users should be able or add to or override the parsers in the /formats directory with an environment variable path or similar?

**Comment by pobocks** [comment]
Yeah, basically - it should load files from A, B, C and since the registry
is a dict, something with the same format_name in a folder processed later
should override.

**Comment by pobocks** [comment]
Closing this as develop currently has this ability.
